In [1]:
import numpy as np

In [3]:
ones_array= np.ones((3,3))

In [5]:
ones_array

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [9]:
ones_arr=np.ones((5,5), dtype=int)

In [11]:
ones_arr

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [13]:
zeros_arr=np.zeros((3,3),dtype=int)

In [15]:
zeros_arr

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [17]:
ones_arr

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [19]:
ones_arr * 255

array([[255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255]])

In [21]:
import matplotlib.pyplot as plt

In [23]:
 %matplotlib inline

In [25]:
from  PIL import Image # python  image library

In [27]:
horse_image=Image.open(r'H:\DATA SCIENCE- Kodi Prakash Senapthi\data science projt\horse.jpg')

In [29]:
horse_image

In [31]:
type(horse_image)

PIL.JpegImagePlugin.JpegImageFile

In [33]:
HORSE_arr=np.asarray(horse_image)  #image converted in array
HORSE_arr

array([[[ 57,  94, 138],
        [ 57,  94, 138],
        [ 57,  94, 138],
        ...,
        [140, 176, 192],
        [139, 175, 191],
        [138, 174, 190]],

       [[ 57,  94, 138],
        [ 57,  94, 138],
        [ 57,  94, 138],
        ...,
        [141, 177, 193],
        [140, 176, 192],
        [138, 174, 190]],

       [[ 57,  94, 138],
        [ 57,  94, 138],
        [ 57,  94, 138],
        ...,
        [142, 178, 194],
        [141, 177, 193],
        [140, 176, 192]],

       ...,

       [[ 71,  90,  26],
        [ 71,  90,  24],
        [ 71,  90,  24],
        ...,
        [ 88, 107,  18],
        [ 89, 108,  19],
        [ 90, 109,  20]],

       [[ 71,  90,  26],
        [ 71,  90,  24],
        [ 71,  90,  24],
        ...,
        [ 87, 106,  17],
        [ 88, 107,  18],
        [ 89, 108,  19]],

       [[ 71,  90,  26],
        [ 71,  90,  24],
        [ 71,  90,  24],
        ...,
        [ 86, 105,  16],
        [ 87, 106,  17],
        [ 88, 107,  18]]

In [47]:
type(HORSE_arr)

numpy.ndarray

In [49]:
plt.imshow(HORSE_arr)   #show the image width and height

In [41]:
HORSE_arr.shape        # height=408 width= 612 & 3 means 3d dimention(rgb)   

(408, 612, 3)

In [43]:
horse_red= HORSE_arr.copy()

In [45]:
horse_red

array([[[ 57,  94, 138],
        [ 57,  94, 138],
        [ 57,  94, 138],
        ...,
        [140, 176, 192],
        [139, 175, 191],
        [138, 174, 190]],

       [[ 57,  94, 138],
        [ 57,  94, 138],
        [ 57,  94, 138],
        ...,
        [141, 177, 193],
        [140, 176, 192],
        [138, 174, 190]],

       [[ 57,  94, 138],
        [ 57,  94, 138],
        [ 57,  94, 138],
        ...,
        [142, 178, 194],
        [141, 177, 193],
        [140, 176, 192]],

       ...,

       [[ 71,  90,  26],
        [ 71,  90,  24],
        [ 71,  90,  24],
        ...,
        [ 88, 107,  18],
        [ 89, 108,  19],
        [ 90, 109,  20]],

       [[ 71,  90,  26],
        [ 71,  90,  24],
        [ 71,  90,  24],
        ...,
        [ 87, 106,  17],
        [ 88, 107,  18],
        [ 89, 108,  19]],

       [[ 71,  90,  26],
        [ 71,  90,  24],
        [ 71,  90,  24],
        ...,
        [ 86, 105,  16],
        [ 87, 106,  17],
        [ 88, 107,  18]]

In [51]:
HORSE_arr==horse_red

array([[[ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True],
        ...,
        [ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]],

       [[ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True],
        ...,
        [ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]],

       [[ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True],
        ...,
        [ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]],

       ...,

       [[ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True],
        ...,
        [ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]],

       [[ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True],
        ...,
        [ True,  True,  True],
        [ True,  True,  True],
        [ True,

In [53]:
plt.imshow(horse_red)

In [55]:
plt.imshow(horse_red[:,:,0])       #cahnge the color of image

In [57]:
horse_red[:,:,0]

array([[ 57,  57,  57, ..., 140, 139, 138],
       [ 57,  57,  57, ..., 141, 140, 138],
       [ 57,  57,  57, ..., 142, 141, 140],
       ...,
       [ 71,  71,  71, ...,  88,  89,  90],
       [ 71,  71,  71, ...,  87,  88,  89],
       [ 71,  71,  71, ...,  86,  87,  88]], dtype=uint8)

In [67]:
plt.imshow(horse_red[:,:,0], cmap='Greys')      #black and gray image

In [76]:
plt.imshow(horse_red[:,:,1], cmap='grey') # #black and white image

In [78]:
plt.imshow(horse_red[:,:,2], cmap='grey') # #black and white image pure 

NOTE - cmap=color map in matplotlib  .colors are given on link just pick up any color.
https://matplotlib.org/stable/users/explain/colors/colormaps.html

In [80]:
plt.imshow(horse_red[:,:,0], cmap='Blues')

In [82]:
plt.imshow(horse_red[:,:,1], cmap='Blues')

In [84]:
plt.imshow(horse_red[:,:,2], cmap='Blues')

In [86]:
horse_red[:,:,0]

array([[ 57,  57,  57, ..., 140, 139, 138],
       [ 57,  57,  57, ..., 141, 140, 138],
       [ 57,  57,  57, ..., 142, 141, 140],
       ...,
       [ 71,  71,  71, ...,  88,  89,  90],
       [ 71,  71,  71, ...,  87,  88,  89],
       [ 71,  71,  71, ...,  86,  87,  88]], dtype=uint8)

In [88]:
horse_red[:,:,1]

array([[ 94,  94,  94, ..., 176, 175, 174],
       [ 94,  94,  94, ..., 177, 176, 174],
       [ 94,  94,  94, ..., 178, 177, 176],
       ...,
       [ 90,  90,  90, ..., 107, 108, 109],
       [ 90,  90,  90, ..., 106, 107, 108],
       [ 90,  90,  90, ..., 105, 106, 107]], dtype=uint8)

In [90]:
horse_red[:,:,2]

array([[138, 138, 138, ..., 192, 191, 190],
       [138, 138, 138, ..., 193, 192, 190],
       [138, 138, 138, ..., 194, 193, 192],
       ...,
       [ 26,  24,  24, ...,  18,  19,  20],
       [ 26,  24,  24, ...,  17,  18,  19],
       [ 26,  24,  24, ...,  16,  17,  18]], dtype=uint8)

In [92]:
horse_red[:,:,1] =0    #convert all in 0

In [96]:
horse_red[:,:,1]  

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [98]:
plt.imshow(horse_red)       #change color .this is called array value manupulation

In [100]:
horse_red[:,:,2]  

array([[138, 138, 138, ..., 192, 191, 190],
       [138, 138, 138, ..., 193, 192, 190],
       [138, 138, 138, ..., 194, 193, 192],
       ...,
       [ 26,  24,  24, ...,  18,  19,  20],
       [ 26,  24,  24, ...,  17,  18,  19],
       [ 26,  24,  24, ...,  16,  17,  18]], dtype=uint8)

In [102]:
horse_red[:,:,2]  =0

In [104]:
horse_red[:,:,2]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [106]:
plt.imshow(horse_red) #red background image

This practical understands that-
1) How image is convert to array by using numpy, matplotlib, pil library.
2) when pixel values changes - array manipulation happened
3) due to array manipulation image also varies
4) This is all power goes to numpy, matplotlib, pil library.
5) you can pick any image ,it will give you proper output.